import './globals.css';

import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';

import getCurrentUser from './actions/getCurrentUser';
import LogInModal from './components/modals/LogInModal';
import Navbar from './components/navbar/Navbar';
import RentModal from './components/modals/RentModal';
import SearchModal from './components/modals/SearchModal';
import SignUpModal from './components/modals/SignUpModal';
import ToasterProvider from './providers/ToasterProvider';

const font = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Airbnb',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const currentUser = await getCurrentUser();

	return (
		<html lang="en">
			<body className={font.className}>
				<ToasterProvider />
				<SearchModal />
				<SignUpModal />
				<LogInModal />
				<RentModal />
				<Navbar currentUser={currentUser} />
				<div className="pb-20 pt-28">{children}</div>
			</body>
		</html>
	);
}
